### PR TITLE
Login and sign up page styling

### PR DESCRIPTION
**Pull request by nickbircher**
image
image

### CODE REVIEW

**Review by ktaschek — COMMENTED** [review]
I'd center everything and make the text color of the inputs the same as the other text colors, otherwise I think it looks good!

**Comment by ryanhu021** [comment]
I agree with Kyle

**Review by ryanhu021 — DISMISSED** [review]
Agree with Kyle

**Comment by amalekia** [comment]
On top of the previous comments I believe making it a little wider would make the page fill up nicer

**Comment by nickbircher** [comment]
Centered and made wider, but I couldn't figure out how to make the placeholder text white.  No matter what, it would create a duplicate placeholder over it in black.
The closest I got was something like this in login-signup.css:  `.field::-webkit-input-placeholder { 
    color: #fff !important;
}
.field:-moz-placeholder {
   color: #fff !important;
   opacity:  1;
}
.field::-moz-placeholder {
   color: #fff !important;
   opacity: 1;
}
.field:-ms-input-placeholder {
   color: #fff !important;
}

.form-control:not(active){
  color: white !important;
 }

.form-control:focus{
  color: white !important;
 }`

**Comment by ktaschek** [comment]
I think I got the color. Ryan said that it might be taking the color from the wrapper so I put the color property in there and it worked 💀

**Pull request merged**
